### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ilabdsf** [zeroflag/punyforth#11]
What is the license? I would suggest CC0/Unlicense as Forths are traditionally public domain if it is not decided yet, but for now I have not found any information about license at all.

**Comment by zeroflag** [comment]
I haven't thought about it yet. Most of my other stuffs are MIT of BSD. But I'm not an license exepert, I have to check what CC0/Unlicense mean first.

**Comment by zeroflag** [comment]
I added the license.txt
