### ISSUE TITLE
OSX .jar files

### ISSUE THREAD

**Issue by alport** [zeroflag/punyforth#18]
The contribution by Craig A. Lindley lists the prerequisite files:
1. ESP8266PunyForthLoader.jar
2. jssc.jar (version 2.6.0 or newer)

He does supply jssc.jar, but not ESP8266PunyForthLoader.jar - only: ESP8266PunyForthLoader.java
Is ESP8266PunyForthLoader.jar or can it be generated from the ESP8266PunyForthLoader.java?

**Comment by zeroflag** [comment]
I added the jar file.
