### ISSUE TITLE
request to flush out getting started docs.

### ISSUE THREAD

**Issue by mhoffma** [zeroflag/punyforth#26]
On your page that describes setup you should also point out,(sorry if I missed it) you need to run modules.py and select a program to install as uber.forth.

serial connection requires local echo and crlf and delbs swap.

```
(trusty)mmh@localhost:~/esp/forth/esp-open-rtos/examples/punyforth/arch/esp8266/bin$ picocom /dev/ttyUSB4 -b 115200 --omap crlf --echo --imap delbs
picocom v1.7

port is        : /dev/ttyUSB4
flowcontrol    : none
baudrate is    : 115200
parity is      : none
databits are   : 8
escape is      : C-a
local echo is  : yes
noinit is      : no
noreset is     : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv
imap is        : delbs,
omap is        : crlf,
emap is        : crcrlf,delbs,

Terminal ready

(stack 0 10) 

```

BTW this is a really cool program very light weight.

**Comment by zeroflag** [comment]
Yes, I agree that this need to be clarified a bit more as it confused other people too. Probably I'll write a separate page about this and link it to the readme.

**Comment by zeroflag** [comment]
Hi,

I added a new page https://github.com/zeroflag/punyforth/wiki/Developing-Punyforth-applications

Let me know if you think there is anything missing.

**Comment by GerardSontag** [comment]
Hello,
May be you can add the ability to send files as soon as you have flashed punyforth.
I am using Tera Term as the terminal emulator and it let me send files by simply doing a drag n drop of the file. I've seen that Picocom let you send files too.
I other words you don't need to reflash your source as long as it's not working/perfect but in case of crash or reset you need to resend your file(s).
Add something like 
-mytest
marker: -mytest
at the beginning of your file and you're ready!

**Comment by zeroflag** [comment]
Good point, I'll add this tool.

**Comment by zeroflag** [comment]
I added a short section about sending files, and using the marker: word.

https://github.com/zeroflag/punyforth/wiki/Developing-Punyforth-applications
