### ISSUE TITLE
when i flash puny forth i get the same error , see file

### ISSUE THREAD

**Issue by kedewey** [zeroflag/punyforth#37]
kendo@kdewey:~/Downloads/punyforth-master/arch/esp8266/bin > python flash.py /dev/ttyUSB0
Selected modules: ALL
Flashing binaries..
Flashing 0x0: rboot.bin, 0x1000: blank_config.bin, 0x2000: punyforth.bin
Connecting...
Erasing flash...
Took 0.16s to erase flash block
Writing at 0x00000000... (25 %)
Writing at 0x00000400... (50 %)
Writing at 0x00000800... (75 %)
Writing at 0x00000c00... (100 %)
Wrote 4096 bytes at 0x00000000 in 0.4 seconds (83.2 kbit/s)...
Erasing flash...
Took 0.17s to erase flash block
Writing at 0x00001000... (50 %)
Writing at 0x00001400... (100 %)
Wrote 2048 bytes at 0x00001000 in 0.2 seconds (83.7 kbit/s)...
Erasing flash...
Took 2.22s to erase flash block
Writing at 0x00002000... (0 %)
Writing at 0x00002400... (0 %)
Writing at 0x00002800... (0 %)
Writing at 0x00002c00... (1 %)
Writing at 0x00003000... (1 %)
Writing at 0x00003400... (1 %)
Writing at 0x00003800... (2 %)
Writing at 0x00003c00... (2 %)
Writing at 0x00004000... (2 %)
Writing at 0x00004400... (3 %)
Writing at 0x00004800... (3 %)
Writing at 0x00004c00... (3 %)
Writing at 0x00005000... (4 %)
Writing at 0x00005400... (4 %)
Writing at 0x00005800... (4 %)
Writing at 0x00005c00... (5 %)
Writing at 0x00006000... (5 %)
Writing at 0x00006400... (5 %)
Writing at 0x00006800... (6 %)
Writing at 0x00006c00... (6 %)
Writing at 0x00007000... (6 %)
Writing at 0x00007400... (7 %)
Writing at 0x00007800... (7 %)
Writing at 0x00007c00... (7 %)
Writing at 0x00008000... (8 %)
Writing at 0x00008400... (8 %)
Writing at 0x00008800... (8 %)
Writing at 0x00008c00... (9 %)
Writing at 0x00009000... (9 %)
Writing at 0x00009400... (9 %)
Writing at 0x00009800... (10 %)
Writing at 0x00009c00... (10 %)
Writing at 0x0000a000... (10 %)
Writing at 0x0000a400... (11 %)
Writing at 0x0000a800... (11 %)
Writing at 0x0000ac00... (11 %)
Writing at 0x0000b000... (12 %)
Writing at 0x0000b400... (12 %)
Writing at 0x0000b800... (12 %)
Writing at 0x0000bc00... (13 %)
Writing at 0x0000c000... (13 %)
Writing at 0x0000c400... (13 %)
Writing at 0x0000c800... (14 %)
Writing at 0x0000cc00... (14 %)
Writing at 0x0000d000... (14 %)
Writing at 0x0000d400... (15 %)
Writing at 0x0000d800... (15 %)
Writing at 0x0000dc00... (15 %)
Writing at 0x0000e000... (16 %)
Writing at 0x0000e400... (16 %)
Writing at 0x0000e800... (16 %)
Writing at 0x0000ec00... (17 %)
Writing at 0x0000f000... (17 %)
Writing at 0x0000f400... (17 %)
Writing at 0x0000f800... (18 %)
Writing at 0x0000fc00... (18 %)
Writing at 0x00010000... (18 %)
Writing at 0x00010400... (19 %)
Writing at 0x00010800... (19 %)
Writing at 0x00010c00... (19 %)
Writing at 0x00011000... (20 %)
Writing at 0x00011400... (20 %)
Writing at 0x00011800... (20 %)
Writing at 0x00011c00... (21 %)
Writing at 0x00012000... (21 %)
Writing at 0x00012400... (21 %)
Writing at 0x00012800... (22 %)
Writing at 0x00012c00... (22 %)
Writing at 0x00013000... (22 %)
Writing at 0x00013400... (23 %)
Writing at 0x00013800... (23 %)
Writing at 0x00013c00... (23 %)
Writing at 0x00014000... (24 %)
Writing at 0x00014400... (24 %)
Writing at 0x00014800... (24 %)
Writing at 0x00014c00... (25 %)
Writing at 0x00015000... (25 %)
Writing at 0x00015400... (25 %)
Writing at 0x00015800... (25 %)
Writing at 0x00015c00... (26 %)
Writing at 0x00016000... (26 %)
Writing at 0x00016400... (26 %)
Writing at 0x00016800... (27 %)
Writing at 0x00016c00... (27 %)
Writing at 0x00017000... (27 %)
Writing at 0x00017400... (28 %)
Writing at 0x00017800... (28 %)
Writing at 0x00017c00... (28 %)
Writing at 0x00018000... (29 %)
Writing at 0x00018400... (29 %)
Writing at 0x00018800... (29 %)
Writing at 0x00018c00... (30 %)
Writing at 0x00019000... (30 %)
Writing at 0x00019400... (30 %)
Writing at 0x00019800... (31 %)
Writing at 0x00019c00... (31 %)
Writing at 0x0001a000... (31 %)
Writing at 0x0001a400... (32 %)
Writing at 0x0001a800... (32 %)
Writing at 0x0001ac00... (32 %)
Writing at 0x0001b000... (33 %)
Writing at 0x0001b400... (33 %)
Writing at 0x0001b800... (33 %)
Writing at 0x0001bc00... (34 %)
Writing at 0x0001c000... (34 %)
Writing at 0x0001c400... (34 %)
Writing at 0x0001c800... (35 %)
Writing at 0x0001cc00... (35 %)
Writing at 0x0001d000... (35 %)
Writing at 0x0001d400... (36 %)
Writing at 0x0001d800... (36 %)
Writing at 0x0001dc00... (36 %)
Writing at 0x0001e000... (37 %)
Writing at 0x0001e400... (37 %)
Writing at 0x0001e800... (37 %)
Writing at 0x0001ec00... (38 %)
Writing at 0x0001f000... (38 %)
Writing at 0x0001f400... (38 %)
Writing at 0x0001f800... (39 %)
Writing at 0x0001fc00... (39 %)
Writing at 0x00020000... (39 %)
Writing at 0x00020400... (40 %)
Writing at 0x00020800... (40 %)
Writing at 0x00020c00... (40 %)
Writing at 0x00021000... (41 %)
Writing at 0x00021400... (41 %)
Writing at 0x00021800... (41 %)
Writing at 0x00021c00... (42 %)
Writing at 0x00022000... (42 %)
Writing at 0x00022400... (42 %)
Writing at 0x00022800... (43 %)
Writing at 0x00022c00... (43 %)
Writing at 0x00023000... (43 %)
Writing at 0x00023400... (44 %)
Writing at 0x00023800... (44 %)
Writing at 0x00023c00... (44 %)
Writing at 0x00024000... (45 %)
Writing at 0x00024400... (45 %)
Writing at 0x00024800... (45 %)
Writing at 0x00024c00... (46 %)
Writing at 0x00025000... (46 %)
Writing at 0x00025400... (46 %)
Writing at 0x00025800... (47 %)
Writing at 0x00025c00... (47 %)
Writing at 0x00026000... (47 %)
Writing at 0x00026400... (48 %)
Writing at 0x00026800... (48 %)
Writing at 0x00026c00... (48 %)
Writing at 0x00027000... (49 %)
Writing at 0x00027400... (49 %)
Writing at 0x00027800... (49 %)
Writing at 0x00027c00... (50 %)
Writing at 0x00028000... (50 %)
Writing at 0x00028400... (50 %)
Writing at 0x00028800... (50 %)
Writing at 0x00028c00... (51 %)
Writing at 0x00029000... (51 %)
Writing at 0x00029400... (51 %)
Writing at 0x00029800... (52 %)
Writing at 0x00029c00... (52 %)
Writing at 0x0002a000... (52 %)
Writing at 0x0002a400... (53 %)
Writing at 0x0002a800... (53 %)
Writing at 0x0002ac00... (53 %)
Writing at 0x0002b000... (54 %)
Writing at 0x0002b400... (54 %)
Writing at 0x0002b800... (54 %)
Writing at 0x0002bc00... (55 %)
Writing at 0x0002c000... (55 %)
Writing at 0x0002c400... (55 %)
Writing at 0x0002c800... (56 %)
Writing at 0x0002cc00... (56 %)
Writing at 0x0002d000... (56 %)
Writing at 0x0002d400... (57 %)
Writing at 0x0002d800... (57 %)
Writing at 0x0002dc00... (57 %)
Writing at 0x0002e000... (58 %)
Writing at 0x0002e400... (58 %)
Writing at 0x0002e800... (58 %)
Writing at 0x0002ec00... (59 %)
Writing at 0x0002f000... (59 %)
Writing at 0x0002f400... (59 %)
Writing at 0x0002f800... (60 %)
Writing at 0x0002fc00... (60 %)
Writing at 0x00030000... (60 %)
Writing at 0x00030400... (61 %)
Writing at 0x00030800... (61 %)
Writing at 0x00030c00... (61 %)
Writing at 0x00031000... (62 %)
Writing at 0x00031400... (62 %)
Writing at 0x00031800... (62 %)
Writing at 0x00031c00... (63 %)
Writing at 0x00032000... (63 %)
Writing at 0x00032400... (63 %)
Writing at 0x00032800... (64 %)
Writing at 0x00032c00... (64 %)
Writing at 0x00033000... (64 %)
Writing at 0x00033400... (65 %)
Writing at 0x00033800... (65 %)
Writing at 0x00033c00... (65 %)
Writing at 0x00034000... (66 %)
Writing at 0x00034400... (66 %)
Writing at 0x00034800... (66 %)
Writing at 0x00034c00... (67 %)
Writing at 0x00035000... (67 %)
Writing at 0x00035400... (67 %)
Writing at 0x00035800... (68 %)
Writing at 0x00035c00... (68 %)
Writing at 0x00036000... (68 %)
Writing at 0x00036400... (69 %)
Writing at 0x00036800... (69 %)
Writing at 0x00036c00... (69 %)
Writing at 0x00037000... (70 %)
Writing at 0x00037400... (70 %)
Writing at 0x00037800... (70 %)
Writing at 0x00037c00... (71 %)
Writing at 0x00038000... (71 %)
Writing at 0x00038400... (71 %)
Writing at 0x00038800... (72 %)
Writing at 0x00038c00... (72 %)
Writing at 0x00039000... (72 %)
Writing at 0x00039400... (73 %)
Writing at 0x00039800... (73 %)
Writing at 0x00039c00... (73 %)
Writing at 0x0003a000... (74 %)
Writing at 0x0003a400... (74 %)
Writing at 0x0003a800... (74 %)
Writing at 0x0003ac00... (75 %)
Writing at 0x0003b000... (75 %)
Writing at 0x0003b400... (75 %)
Writing at 0x0003b800... (75 %)
Writing at 0x0003bc00... (76 %)
Writing at 0x0003c000... (76 %)
Writing at 0x0003c400... (76 %)
Writing at 0x0003c800... (77 %)
Writing at 0x0003cc00... (77 %)
Writing at 0x0003d000... (77 %)
Writing at 0x0003d400... (78 %)
Writing at 0x0003d800... (78 %)
Writing at 0x0003dc00... (78 %)
Writing at 0x0003e000... (79 %)
Writing at 0x0003e400... (79 %)
Writing at 0x0003e800... (79 %)
Writing at 0x0003ec00... (80 %)
Writing at 0x0003f000... (80 %)
Writing at 0x0003f400... (80 %)
Writing at 0x0003f800... (81 %)
Writing at 0x0003fc00... (81 %)
Writing at 0x00040000... (81 %)
Writing at 0x00040400... (82 %)
Writing at 0x00040800... (82 %)
Writing at 0x00040c00... (82 %)
Writing at 0x00041000... (83 %)
Writing at 0x00041400... (83 %)
Writing at 0x00041800... (83 %)
Writing at 0x00041c00... (84 %)
Writing at 0x00042000... (84 %)
Writing at 0x00042400... (84 %)
Writing at 0x00042800... (85 %)
Writing at 0x00042c00... (85 %)
Writing at 0x00043000... (85 %)
Writing at 0x00043400... (86 %)
Writing at 0x00043800... (86 %)
Writing at 0x00043c00... (86 %)
Writing at 0x00044000... (87 %)
Writing at 0x00044400... (87 %)
Writing at 0x00044800... (87 %)
Writing at 0x00044c00... (88 %)
Writing at 0x00045000... (88 %)
Writing at 0x00045400... (88 %)
Writing at 0x00045800... (89 %)
Writing at 0x00045c00... (89 %)
Writing at 0x00046000... (89 %)
Writing at 0x00046400... (90 %)
Writing at 0x00046800... (90 %)
Writing at 0x00046c00... (90 %)
Writing at 0x00047000... (91 %)
Writing at 0x00047400... (91 %)
Writing at 0x00047800... (91 %)
Writing at 0x00047c00... (92 %)
Writing at 0x00048000... (92 %)
Writing at 0x00048400... (92 %)
Writing at 0x00048800... (93 %)
Writing at 0x00048c00... (93 %)
Writing at 0x00049000... (93 %)
Writing at 0x00049400... (94 %)
Writing at 0x00049800... (94 %)
Writing at 0x00049c00... (94 %)
Writing at 0x0004a000... (95 %)
Writing at 0x0004a400... (95 %)
Writing at 0x0004a800... (95 %)
Writing at 0x0004ac00... (96 %)
Writing at 0x0004b000... (96 %)
Writing at 0x0004b400... (96 %)
Writing at 0x0004b800... (97 %)
Writing at 0x0004bc00... (97 %)
Writing at 0x0004c000... (97 %)
Writing at 0x0004c400... (98 %)
Writing at 0x0004c800... (98 %)
Writing at 0x0004cc00... (98 %)
Writing at 0x0004d000... (99 %)
Writing at 0x0004d400... (99 %)
Writing at 0x0004d800... (99 %)
Writing at 0x0004dc00... (100 %)
Wrote 311296 bytes at 0x00002000 in 30.2 seconds (82.4 kbit/s)...

Leaving...
Flashing LAYOUT.tmp
Connecting...
Erasing flash...
Took 0.15s to erase flash block
Writing at 0x00051000... (100 %)
Wrote 1024 bytes at 0x00051000 in 0.1 seconds (85.4 kbit/s)...

Leaving...
Flashing 0x52000: APP.tmp, 0x53000: CORE.tmp, 0x56000: DHT22.tmp, 0x57000: FLASH.tmp, 0x58000: FONT57.tmp, 0x59000: GPIO.tmp, 0x5a000: MAILBOX.tmp, 0x5b000: NETCON.tmp, 0x5d000: NTP.tmp, 0x5e000: PING.tmp, 0x5f000: SONOFF.tmp, 0x60000: SSD1306I2C.tmp, 0x62000: SSD1306SPI.tmp, 0x64000: TASKS.tmp, 0x65000: TCPREPL.tmp, 0x66000: TURNKEY.tmp, 0x67000: WIFI.tmp, 0x68000: EVENT.tmp, 0x69000: RINGBUF.tmp, 0x6a000: DECOMP.tmp, 0x6b000: PUNIT.tmp
Connecting...
Erasing flash...
Took 0.10s to erase flash block
Writing at 0x00052000... (100 %)
Wrote 1024 bytes at 0x00052000 in 0.1 seconds (86.3 kbit/s)...
Erasing flash...
Took 0.22s to erase flash block
Writing at 0x00053000... (9 %)
Writing at 0x00053400... (18 %)
Writing at 0x00053800... (27 %)
Writing at 0x00053c00... (36 %)
Writing at 0x00054000... (45 %)
Writing at 0x00054400... (54 %)
Writing at 0x00054800... (63 %)
Writing at 0x00054c00... (72 %)
Writing at 0x00055000... (81 %)
Writing at 0x00055400... (90 %)
Writing at 0x00055800... (100 %)
Wrote 11264 bytes at 0x00053000 in 1.1 seconds (84.5 kbit/s)...
Erasing flash...
Took 0.13s to erase flash block
Writing at 0x00056000... (50 %)
Writing at 0x00056400... (100 %)
Wrote 2048 bytes at 0x00056000 in 0.2 seconds (84.6 kbit/s)...
Erasing flash...
Took 0.09s to erase flash block
Writing at 0x00057000... (50 %)
Writing at 0x00057400... (100 %)
Wrote 2048 bytes at 0x00057000 in 0.2 seconds (85.0 kbit/s)...
Erasing flash...
Took 0.13s to erase flash block
Writing at 0x00058000... (25 %)
Writing at 0x00058400... (50 %)
Writing at 0x00058800... (75 %)
Writing at 0x00058c00... (100 %)
Wrote 4096 bytes at 0x00058000 in 0.4 seconds (84.5 kbit/s)...
Erasing flash...
Took 0.09s to erase flash block
Writing at 0x00059000... (100 %)
Wrote 1024 bytes at 0x00059000 in 0.1 seconds (84.6 kbit/s)...
Erasing flash...
Took 0.13s to erase flash block
Writing at 0x0005a000... (100 %)
Wrote 1024 bytes at 0x0005a000 in 0.1 seconds (85.4 kbit/s)...
Erasing flash...
Took 0.09s to erase flash block
Writing at 0x0005b000... (20 %)
Writing at 0x0005b400... (40 %)
Writing at 0x0005b800... (60 %)
Writing at 0x0005bc00... (80 %)
Writing at 0x0005c000... (100 %)
Wrote 5120 bytes at 0x0005b000 in 0.5 seconds (84.9 kbit/s)...
Erasing flash...
Took 0.13s to erase flash block
Writing at 0x0005d000... (50 %)
Writing at 0x0005d400... (100 %)
Wrote 2048 bytes at 0x0005d000 in 0.2 seconds (85.4 kbit/s)...
Erasing flash...
Took 0.09s to erase flash block
Writing at 0x0005e000... (50 %)
Writing at 0x0005e400... (100 %)
Wrote 2048 bytes at 0x0005e000 in 0.2 seconds (85.4 kbit/s)...
Erasing flash...
Took 0.12s to erase flash block
Writing at 0x0005f000... (100 %)
Wrote 1024 bytes at 0x0005f000 in 0.1 seconds (85.4 kbit/s)...
Erasing flash...
Took 0.09s to erase flash block
Writing at 0x00060000... (16 %)

A fatal error occurred: Invalid head of packet
ken

**Comment by zeroflag** [comment]
Why kind of board do you have? Can you try it with _--flashmode dio_ parameter?

**Comment by zeroflag** [comment]
I added a note about this to the readme.

https://github.com/zeroflag/punyforth/commit/653ef3c05c2efe635a079647326b0d8b3e9d25dd#diff-04c6e90faac2675aa89e2176d2eec7d8
