### ISSUE TITLE
Flashing error in SSD1

### ISSUE THREAD

**Issue by graphoid** [zeroflag/punyforth#42]
quickstart using flash.py

Flashing fails at;
Erasing flash...
Took 0.08s to erase flash block
Writing at 0x00060000... (16 %)
Writing at 0x00060400... (33 %)

A fatal error occurred: Invalid head of packet

bad bin image?

**Comment by zeroflag** [comment]
Hi,

Have you tried flashing with --flashmode qio ?

**Comment by graphoid** [comment]
tried --flashmode qio, same error (is it default mode anyway?)
--flashmode dio , success!

Thanks, should have investigated all options first!
