### ISSUE TITLE
Minor inconsistency in documentation.

### ISSUE THREAD

**Issue by yrabbit** [zeroflag/punyforth#46]
On page https://github.com/zeroflag/punyforth 
``Let's assume the serial port is COM3.''. But the figure uses COM4.
![com-port](https://user-images.githubusercontent.com/6075465/52893744-9f3a8980-31eb-11e9-9585-fcc79a917612.png)

**Comment by zeroflag** [comment]
Thanks @yrabbit, I fixed it.
