### ISSUE TITLE
Need "words" word

### ISSUE THREAD

**Issue by CraigLindley** [zeroflag/punyforth#6]
It would be nice if you could add a "words" word so that we could see all of the words currently defined in the dictionary.

**Comment by zeroflag** [comment]
Thanks for your suggestion. What would the "words" word do? Just print out the word names from the dictionary? There is a "help" word that does this.

**Comment by CraigLindley** [comment]
That works perfectly so I'll close this issue. Thanks for the fast response even on Christmas day

**Comment by profburke** [comment]
You might want to mention the "help" word in the readme. Many forthwrights will expect "words" and some number of them will be as dense as me and not think to try "help" :)

**Comment by zeroflag** [comment]
Ok, I added it to the readme.
